---
- hosts: localhost
  tasks:
    - name: print facts {uses only the last msg only}
      debug:
        msg: "IPv4 address: {{ ansible_default_ipv4.address }}"
    
    - name: print multiple facts
      debug:
        msg: "IPv4 alias: {{ansible_default_ipv4.alias}}"