---
- hosts: localhost
  vars:
    - user: vijay
  tasks:
    - name: Check if file already exists
      command: ls /mnt/c/Users/{{user}}/ansible/createfile.txt
      register: file_exists
      ignore_errors: yes

    - name: create file for user
      file:
        path: /mnt/c/Users/{{user}}/ansible/createfile.txt
        state: touch
      when: file_exists is failed

    - name: show message if file exists
      debug:
        msg: The user file already exists.
      when: file_exists is succeeded