---
- name: Download Teamcity from Jetbrains and Install as Service
  hosts: localhost
  vars:
    download_url: https://download.jetbrains.com/teamcity/TeamCity-2022.10.3.tar.gz
  tasks:
   - name: Download Open JDK
     become: yes
     apt:
      name: openjdk-8-jre-headless
      update_cache: yes
      state: present
  
   - name: validate if Java is availble 
     shell: 
      java -version
     
   - name: Create the group
     become: yes
     group: 
      name: teamcity
      state: present

   - name: Create the user
     become: yes
     user:
        name: tcuser
        state: present

   - name: Create a Directory /opt/teamcity
     become: yes
     file:
       path: /opt/teamcity
       state: directory
       mode: 0755
       owner: teamcity
       group: tcuser

   - name: Download Teamcity using unarchive
     become: yes
     unarchive:
       src: "{{download_url}}"
       dest: /opt/teamcity
       mode: 0755
       remote_src: yes
       group: teamcity
       owner: tcuser

   - name: Creating a service file
     become: yes
     copy: 
      content: |-
        [Unit]
        Description=Teamcity Service
        Requires=network.target
        After=network.target

        [Service]
        Type=forking
        User=tcuser
        Environment="TEAMCITY_HOME=/opt/teamcity"
    
        ExecStart=/opt/teamcity/bin/runAll.sh start
        ExecStop=/opt/teamcity/bin/runAll.sh stop
        Restart=on-abnormal

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/teamcity.service

   - name: Reload the SystemD to re-read configurations
     become: yes
     systemd:
        daemon-reload: yes

   - name: Enable the teamcity service and start
     become: yes
     systemd:
        name: teamcity
        enabled: yes
        state: started

   - name: Connect to Tomcat server on port 8111 and check status 200 - Try 5 times
     tags: test
     uri:
       url: http://localhost:8111
     register: result
     until: "result.status == 200"
     retries: 5
     delay: 10